railsdemos/railsdemo/config/routes.rb
Rails.application.routes.draw do
  get 'directory/search'

  get 'directory/results'

  resources :students
  resources :classrooms

end

railsdemos/railsdemo/app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates :teacher, :grade, :classid, :presence => true
  validates :teacher, length: { minimum: 2 }
  validates :grade, numericality: {greater_than: 0}

end

railsdemos/railsdemo/app/models/student.rb
class Student < ActiveRecord::Base
  validates :phone, length:{in: 7..10,
                            message:"Your phone number must have 7-10 digits" }

end

railsdemos/railsdemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railsdemos/railsdemo/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @students = Student.where(:classid => @classroom.classid).all
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:teacher, :grade, :classid)
    end
end

railsdemos/railsdemo/app/controllers/directory_controller.rb
class DirectoryController < ApplicationController
  def search
  end

  def results
    @partial_name = "%" + params[:partial_name] + "%"
    @students = Student.where("fullname like ?",
                              @partial_name)

  end
end

railsdemos/railsdemo/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:fullname, :phone, :classid)
    end
end

railsdemos/railsdemo/app/helpers/application_helper.rb
module ApplicationHelper
end

railsdemos/railsdemo/app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

railsdemos/railsdemo/app/helpers/directory_helper.rb
module DirectoryHelper
end

railsdemos/railsdemo/app/helpers/students_helper.rb
module StudentsHelper
end

railsdemos/railsdemo/app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :classid %><br>
    <%= f.text_field :classid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsdemos/railsdemo/app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

railsdemos/railsdemo/app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Grade</th>
      <th>Classid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.teacher %></td>
        <td><%= classroom.grade %></td>
        <td><%= classroom.classid %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

railsdemos/railsdemo/app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

railsdemos/railsdemo/app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @classroom.teacher %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @classroom.grade %>
</p>

<p>
  <strong>Classid:</strong>
  <%= @classroom.classid %>
</p>

<p>
  <strong>Number of students:</strong>
  <%= @students.count %>
</p>

<table>
  <thead>
  <tr>
    <th>Fullname</th>
    <th>Phone</th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>
      <tr>
        <td><%= student.fullname %></td>
        <td><%= student.phone %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>

railsdemos/railsdemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cs416latedemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsdemos/railsdemo/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :classid %><br>
    <%= f.text_field :classid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsdemos/railsdemo/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

railsdemos/railsdemo/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Phone</th>
      <th>Classid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.fullname %></td>
        <td><%= student.phone %></td>
        <td><%= student.classid %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

railsdemos/railsdemo/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

railsdemos/railsdemo/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @student.fullname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Classid:</strong>
  <%= @student.classid %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>